// Generated from the Mercrowave iOS app's Swift data files.
const DAYS = [
 {
  "m": 6,
  "d": 7,
  "w": "Sunday",
  "sign": "Pisces",
  "emoji": "🌗",
  "headline": "CLTC 1 begins under a dreamy Pisces Moon",
  "vibe": "Arrival day with the softest Moon in the zodiac overhead. First-day nerves get a gentle landing.",
  "detail": "The Moon is drifting through Pisces — imaginative, sensitive, a little homesick-prone by night. The waning Moon means the sky is in wind-down mode, clearing space for the New Moon on June 14. Translation: the summer's story hasn't started being written yet. You're early. Mercury is direct; the microwave is closed and humming.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 8,
  "w": "Monday",
  "sign": "Pisces",
  "emoji": "🌘",
  "headline": "Pisces Moon — soft launch continues",
  "vibe": "Everyone's still figuring out where the bathrooms are. Feelings are close to the surface; so is laughter.",
  "detail": "Day two of the Pisces Moon keeps things tender and a little dreamy. Good for icebreakers that are actually sincere. The microwave is closed. Enjoy the fully functional appliance era.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 9,
  "w": "Tuesday",
  "sign": "Aries",
  "emoji": "🌘",
  "headline": "Moon enters Aries — the energy arrives",
  "vibe": "The camp wakes UP. First real burst of competitive spirit. Someone sprints somewhere for no reason.",
  "detail": "At 4:33 AM Eastern the Moon charges into Aries — the zodiac's starter pistol. Aries Moons are bold, impatient, and great for first tries. With the Moon nearly dark, energy is raw and unpolished. Perfect for a program that's just getting rolling.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 10,
  "w": "Wednesday",
  "sign": "Aries",
  "emoji": "🌘",
  "headline": "Aries Moon — leap first, apologize later",
  "vibe": "Hands shoot up before questions finish. Field games get spicy.",
  "detail": "A full day of Aries Moon impulsiveness. Channel it: volunteer, run for something, go first. The dark Moon (New Moon in four days) keeps the stakes low — the sky isn't keeping score yet.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 11,
  "w": "Thursday",
  "sign": "Taurus",
  "emoji": "🌘",
  "headline": "Moon enters Taurus — snack-based diplomacy",
  "vibe": "The pace settles. Food tastes better. Friendships form over shared desserts.",
  "detail": "The Moon slides into Taurus at 8:28 AM Eastern — comfort, patience, and snacks. After two hot-headed Aries days, the group finds its rhythm. Steady is the vibe.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 12,
  "w": "Friday",
  "sign": "Taurus",
  "emoji": "🌘",
  "headline": "Mercury enters the retrograde shadow",
  "vibe": "The microwave passes its LAST inspection. Officially: the countdown to chaos begins (June 29). Unofficially: nothing feels different yet.",
  "detail": "Today Mercury crosses the degree it will later retrograde back to — the start of the 'pre-retrograde shadow.' Astrologers treat this as the opening chapter of the retrograde story: the topics that glitch in July quietly introduce themselves now. The microwave is still closed… but it just got its final safety sticker.",
  "rx": false,
  "cazimi": false,
  "big": true
 },
 {
  "m": 6,
  "d": 13,
  "w": "Saturday",
  "sign": "Gemini",
  "emoji": "🌘",
  "headline": "Moon enters Gemini — Shabbat chatter",
  "vibe": "The talkative Moon meets a camp full of people who just met. The volume rises accordingly.",
  "detail": "The Moon enters quick, curious Gemini at 9:06 AM Eastern, joining the Sun there. The darkest nights of the month — tomorrow's New Moon means real stargazing if you can find the stars through the conversation.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 14,
  "w": "Sunday",
  "sign": "Gemini",
  "emoji": "🌑",
  "headline": "NEW MOON in Gemini — the summer officially loads",
  "vibe": "The sky's monthly reset button, in the sign of friendship and words. Intentions set tonight get the whole summer behind them.",
  "detail": "The New Moon lands in Gemini — Sun and Moon aligned in the sign of communication, curiosity, and making friends fast. New Moons are for beginnings, and this one belongs to every teen unpacking a duffel bag in Pennsylvania. Write the intention down. The sky is listening.",
  "rx": false,
  "cazimi": false,
  "big": true
 },
 {
  "m": 6,
  "d": 15,
  "w": "Monday",
  "sign": "Cancer",
  "emoji": "🌒",
  "headline": "Moon enters Cancer — found-family feelings",
  "vibe": "First flicker of 'these are my people.' Homesickness and belonging, somehow at the same time.",
  "detail": "The Moon moves into Cancer at 8:14 AM Eastern — home, comfort, belonging. The first sliver of the waxing crescent appears after sunset: the summer's story has officially begun writing itself.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 16,
  "w": "Tuesday",
  "sign": "Cancer",
  "emoji": "🌒",
  "headline": "Cancer Moon — the group softens",
  "vibe": "Deeper conversations at meals. Someone shares something real and it changes the whole cabin.",
  "detail": "Day two of the Cancer Moon builds emotional glue. This is the transit that turns a random room assignment into a group chat that outlives the summer.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 17,
  "w": "Wednesday",
  "sign": "Leo",
  "emoji": "🌒",
  "headline": "Moon enters Leo — main character hours",
  "vibe": "Confidence spike across the board. Talent-show energy even if there's no talent show.",
  "detail": "The Moon struts into Leo at 8:05 AM Eastern. Leo Moons love an audience, a spotlight, and a bit. Big day for stepping up in front of the group — the sky is handing out courage.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 18,
  "w": "Thursday",
  "sign": "Leo",
  "emoji": "🌒",
  "headline": "Leo Moon — courage compounds",
  "vibe": "Yesterday's brave people inspire today's brave people. The shy kid from Sunday leads an activity.",
  "detail": "The waxing crescent in Leo keeps the confidence flowing. Leadership training under a Leo Moon is the astrological equivalent of a tailwind.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 19,
  "w": "Friday",
  "sign": "Virgo",
  "emoji": "🌒",
  "headline": "Moon enters Virgo — it all gets organized",
  "vibe": "Clipboards appear. Plans crystallize. Someone color-codes something and everyone is grateful.",
  "detail": "The Moon enters practical Virgo at 10:36 AM Eastern, and the First Quarter Moon marks the 'do the work' phase of the lunar cycle. Great for committees, planning blocks, and actually finishing the craft project.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 20,
  "w": "Saturday",
  "sign": "Virgo",
  "emoji": "🌒",
  "headline": "Eve of the Solstice — the sky inhales",
  "vibe": "Last day of astronomical spring. Tomorrow: peak sunlight, Cancer season, and two more programs arriving.",
  "detail": "The Virgo Moon ties up loose ends while the Sun sits at the very end of Gemini. Tomorrow the Sun hits its highest point of the year. If a summer has a 'night before' feeling, it's tonight.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 21,
  "w": "Sunday",
  "sign": "Libra",
  "emoji": "🌓",
  "headline": "Summer Solstice — Cancer season begins",
  "vibe": "Longest day of the year — on the exact day ILTC and CLTC 2 both begin. The sky is on theme.",
  "detail": "The solstice is the Sun's peak — maximum daylight, a cosmic 'session start' button. The Sun enters Cancer, the sign of home, feelings, and found family, and Cancer season covers nearly all of both arriving programs. The Moon slides into social, everyone-get-along Libra by evening. Mercury is still direct. The microwave door is shut and humming. (CLTC 1: you have one day left — make it loud.)",
  "rx": false,
  "cazimi": false,
  "big": true
 },
 {
  "m": 6,
  "d": 22,
  "w": "Monday",
  "sign": "Libra",
  "emoji": "🌓",
  "headline": "Moon in Libra — friendship speedrun (and CLTC 1's finale)",
  "vibe": "Libra Moon = charm mode. Names get learned, inside jokes form in record time. CLTC 1 graduates under the friendliest Moon there is.",
  "detail": "The Moon spends today in Libra, the sign of partnership and social grace. For the new arrivals it's alliance-formation day; for CLTC 1 it's the goodbye — and a Libra Moon goodbye is warm, huggy, and only slightly dramatic. The waxing Moon is building toward the June 29 Full Moon.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 23,
  "w": "Tuesday",
  "sign": "Libra",
  "emoji": "🌔",
  "headline": "Waxing Moon in Libra — the calm before",
  "vibe": "Still smooth sailing. Enjoy it. The sky is quietly loading three major events for next Monday.",
  "detail": "A gentle day: Moon finishing its Libra transit, no major exact aspects. In the background, Mercury is deep in its pre-retrograde shadow (since June 12) — the retrograde story has technically started, we just can't feel it yet.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 24,
  "w": "Wednesday",
  "sign": "Scorpio",
  "emoji": "🌔",
  "headline": "Moon enters Scorpio — intensity arrives",
  "vibe": "Conversations get real. Secrets get traded after lights-out. Someone's whole life story comes out at dinner.",
  "detail": "At 2:43 AM Eastern the Moon leaves polite Libra for all-or-nothing Scorpio. Scorpio Moons pull feelings from small talk to soul talk. Expect deeper bonding — and slightly more drama per capita.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 25,
  "w": "Thursday",
  "sign": "Scorpio",
  "emoji": "🌔",
  "headline": "Scorpio Moon, day two — loyalty tests",
  "vibe": "Friend groups solidify into something that feels weirdly permanent.",
  "detail": "The Moon continues through Scorpio, the sign of trust and emotional depth. Combined with the still-waxing Moon (getting bigger every night on the walk back to the cabin), attachments intensify fast.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 26,
  "w": "Friday",
  "sign": "Sagittarius",
  "emoji": "🌔",
  "headline": "Moon enters Sagittarius — adventure mode",
  "vibe": "Restless, funny, loud. Perfect Shabbat energy — big songs, bigger opinions, someone starts a debate for fun.",
  "detail": "The Moon fires into Sagittarius at 2:40 PM Eastern — the sign of adventure, humor, and saying the quiet part out loud. Sagittarius Moons are the extroverts of the lunar calendar. Great for ruach; terrible for keeping your voice down.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 27,
  "w": "Saturday",
  "sign": "Sagittarius",
  "emoji": "🌔",
  "headline": "Sagittarius Moon — last carefree day",
  "vibe": "Soak up the chaos-free sky. In 48 hours, three planetary events land at once.",
  "detail": "The Moon is still in buoyant Sagittarius and Mercury is spending its final full weekend moving direct. Astrologers call this the 'storm' phase — Mercury has slowed almost to a standstill in the sky, about to shift into reverse. Back up your feelings now.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 28,
  "w": "Sunday",
  "sign": "Sagittarius",
  "emoji": "🌔",
  "headline": "Mercury stations — the microwave door creaks",
  "vibe": "The sky holds its breath. Mercury is basically motionless tonight. Tomorrow: everything.",
  "detail": "Mercury appears frozen in place today — 'stationing' — the astronomical equivalent of a pause before the rewind. The nearly-full Moon finishes Sagittarius and heads for Capricorn overnight. Tomorrow brings Mercury retrograde + a Full Moon + Jupiter changing signs, all within 24 hours. Sleep well tonight.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 6,
  "d": 29,
  "w": "Monday",
  "sign": "Capricorn",
  "emoji": "🌕",
  "headline": "MERCURY RETROGRADE + FULL MOON + JUPITER ENTERS LEO",
  "vibe": "The single biggest sky day of the summer. Triple event. The microwave door swings OPEN at 1:36 PM Eastern.",
  "detail": "A genuine astrological triple-header, all real, all today:\n\n1. Mercury stations RETROGRADE in Cancer at 1:36 PM Eastern (until July 23). Communication, tech, and plans officially enter rewind mode — in Cancer, so it's emotional: old feelings, old friends, nostalgia.\n\n2. FULL MOON in Capricorn at 7:57 PM Eastern. Full Moons are peak-emotion nights — this one lights up the walk back from evening program.\n\n3. JUPITER ENTERS LEO, beginning a year-long transit. Jupiter is luck and growth; Leo is confidence and main-character energy. For a summer of leadership training, you cannot order a better transit.",
  "rx": true,
  "cazimi": false,
  "big": true
 },
 {
  "m": 6,
  "d": 30,
  "w": "Tuesday",
  "sign": "Capricorn",
  "emoji": "🌖",
  "headline": "Retrograde, day 2 — trust nothing with a battery",
  "vibe": "The group chat delivers messages in the wrong order. Someone's alarm doesn't go off. The AUX cord chooses violence.",
  "detail": "First full day of Mercury retrograde in Cancer. Classic effects: misheard announcements, double-booked rooms, texts that send twice or never. Cancer flavor: everyone is 10% more sensitive about it than usual. Survival rules: confirm plans twice, re-read before sending, blame the planet.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 1,
  "w": "Wednesday",
  "sign": "Aquarius",
  "emoji": "🌖",
  "headline": "Moon enters Aquarius — the group thinks big",
  "vibe": "July begins. Aquarius Moon = collective brainstorm energy. Great day for program planning; weird day for feelings.",
  "detail": "The Moon enters Aquarius at 3:32 PM Eastern — the sign of groups, ideals, and the future. Perfect for leadership workshops and big-vision conversations. Mercury retrograde continues underneath it all, so save every document twice.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 2,
  "w": "Thursday",
  "sign": "Aquarius",
  "emoji": "🌖",
  "headline": "Aquarius Moon — friendship over romance",
  "vibe": "The vibe is platonic and idealistic. Tomorrow, Mars has other plans.",
  "detail": "A steady Aquarius-Moon day — community-minded, a little detached. Behind the scenes, Mars is closing in on Uranus for tomorrow's most electric aspect of the summer. Static in the air.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 3,
  "w": "Friday",
  "sign": "Aquarius",
  "emoji": "🌖",
  "headline": "MARS CONJUNCT URANUS — lightning in a bottle",
  "vibe": "The most electric, unpredictable aspect of the summer. Impulsive plans, sudden moves, someone does something legendary.",
  "detail": "Mars (action, drive, adrenaline) meets Uranus (shock, rebellion, electricity) at 3°52' Gemini. This conjunction happens roughly every two years and is famous for sudden events, restless energy, and zero patience. In chatty Gemini, words fly fast. Channel it into the program — this is 'start the thing NOW' energy. And it's the setup for tomorrow…",
  "rx": true,
  "cazimi": false,
  "big": true
 },
 {
  "m": 7,
  "d": 4,
  "w": "Saturday",
  "sign": "Pisces",
  "emoji": "🌖",
  "headline": "July 4th — the sky schedules its own fireworks",
  "vibe": "Mars-Uranus energy still crackling, now with Mars sextile Neptune and trine Pluto. Explosive, dreamy, AND intense. On Independence Day.",
  "detail": "Real transits today: Mars sextile Neptune (8:44 AM) and Mars trine Pluto (9:06 AM) — power with imagination behind it — while yesterday's Mars-Uranus electricity is still in orb. Translation: fireworks in the sky, fireworks in the sky chart. The Moon slips into dreamy Pisces at 2:30 AM, adding a sentimental filter to the whole day. Happy 4th. 🎆",
  "rx": true,
  "cazimi": false,
  "big": true
 },
 {
  "m": 7,
  "d": 5,
  "w": "Sunday",
  "sign": "Pisces",
  "emoji": "🌖",
  "headline": "Pisces Moon — the sentimental hangover",
  "vibe": "Everyone is tired and tender. Naps are astrologically endorsed. Someone cries at a song and that's fine.",
  "detail": "The Moon drifts through Pisces — the softest, most porous sign — while the waning Moon and Mercury retrograde both pull inward. A recovery day by cosmic design. Journaling hits different today.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 6,
  "w": "Monday",
  "sign": "Aries",
  "emoji": "🌗",
  "headline": "Sun square Saturn — the reality check (CLTC 2's finale)",
  "vibe": "Saturn is the strict camp director of the zodiac, and today it squares the Sun — on CLTC 2's very last day. Growth: confirmed the hard way.",
  "detail": "Sun square Saturn (exact 6:47 AM Eastern) is the classic 'Monday of the sky' transit: friction between what you want and what's required. It's also secretly great for discipline — and weirdly perfect for a graduation day: Saturn is the planet of earned things. CLTC 2, you earned it. The Moon charging into Aries at 11:07 AM helps burn through the sludge (and fuels the goodbye-hug sprints).",
  "rx": true,
  "cazimi": false,
  "big": true
 },
 {
  "m": 7,
  "d": 7,
  "w": "Tuesday",
  "sign": "Aries",
  "emoji": "🌗",
  "headline": "Aries Moon — leap first, think later",
  "vibe": "Impatient, competitive, fun. Field games get intense. Someone volunteers for something before hearing the whole sentence.",
  "detail": "A full day of Aries Moon — the zodiac's sprinter. Under Mercury retrograde, double-check the instructions BEFORE the relay race, not after. Big energy, short fuse, fast forgiveness.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 8,
  "w": "Wednesday",
  "sign": "Taurus",
  "emoji": "🌘",
  "headline": "Moon enters Taurus — snacks and stability",
  "vibe": "The sky finally chills. Comfort food tastes 20% better. Best sleep of the week, astrologically speaking.",
  "detail": "The Moon settles into Taurus at 4:30 PM Eastern — the sign of comfort, food, and refusing to be rushed. After a chaotic stretch (Mars-Uranus, Sun-Saturn), this is the sky's built-in rest stop. The dark waning Moon means deep-quiet nights.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 9,
  "w": "Thursday",
  "sign": "Taurus",
  "emoji": "🌘",
  "headline": "Mercury semi-square Mars — snippy texts",
  "vibe": "Words come out sharper than intended today. Retrograde Mercury clashes with Mars — re-read the message, then re-read it again.",
  "detail": "Mercury (retrograde, in touchy Cancer) makes a scratchy semi-square to Mars at 3:11 PM Eastern. Small miscommunications escalate faster than they should. The fix is comically simple: pause five seconds before replying. The steady Taurus Moon has your back.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 10,
  "w": "Friday",
  "sign": "Gemini",
  "emoji": "🌘",
  "headline": "VENUS MEETS THE SOUTH NODE — karmic ex energy",
  "vibe": "Venus touches the point of the past — DURING Mercury retrograde. Old crushes, old friends, 'why am I thinking about them.' The sky's most gossip-worthy day.",
  "detail": "Venus (love, attraction) conjoins the South Node — the karmic point of everything past — at 0°40' Virgo in the early morning. Astrologers read this as relationships from the past demanding a rematch, and it lands mid-Mercury-retrograde, the transit already famous for 'your ex texts you.' Double karma. If someone from home suddenly resurfaces in your DMs today: the sky called it. The Moon enters chatty Gemini at 6:41 PM, so yes, everyone will be talking about it.",
  "rx": true,
  "cazimi": false,
  "big": true
 },
 {
  "m": 7,
  "d": 11,
  "w": "Saturday",
  "sign": "Gemini",
  "emoji": "🌘",
  "headline": "Gemini Moon — gossip travels at light speed",
  "vibe": "Yesterday's karmic drama gets fully processed via group analysis. The dark Moon makes tonight feel secret and cinematic.",
  "detail": "The Moon in Gemini turns the whole camp into a newsroom — everyone has sources, everyone has takes. Meanwhile the Moon is nearly dark (New Moon lands July 14), the introspective bottom of the lunar cycle. Tomorrow, two new programs arrive on one of the strangest, sweetest sky days of the year.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 12,
  "w": "Sunday",
  "sign": "Gemini",
  "emoji": "🌘",
  "headline": "CAZIMI — Mercury in the heart of the Sun (Kallah & CLTC 3 arrive)",
  "vibe": "The clarity flash. Mid-retrograde, the fog lifts for one day — the exact day two programs begin. The microwave is open, but today the food comes out hot.",
  "detail": "At 9:25 PM Eastern the Sun and retrograde Mercury align exactly — 'cazimi,' from the Arabic for 'in the heart of the Sun.' Astrologers treat the retrograde cazimi as the turning point of the whole cycle: the day confusion briefly parts and the actual insight arrives. Kallah and CLTC 3: you're arriving on the single most insightful day of the retrograde. If a realization hits you today, keep it. Moon enters Cancer at 6:46 PM, right on theme for new-home feelings.",
  "rx": true,
  "cazimi": true,
  "big": true
 },
 {
  "m": 7,
  "d": 13,
  "w": "Monday",
  "sign": "Cancer",
  "emoji": "🌘",
  "headline": "VENUS SQUARE URANUS — the chaotic goodbye (ILTC's finale)",
  "vibe": "Venus (feelings) clashes with Uranus (sudden, unexpected) at 10:26 AM — on ILTC's last day. Surprise confessions, chaotic goodbyes, 'I've liked you all session' energy at the buses.",
  "detail": "You could not script this: on ILTC's final day, Venus squares Uranus — the transit of sudden attractions, unexpected declarations, and emotional plot twists. Venus also makes tense angles to Neptune (fantasy) and Pluto (intensity) through the afternoon. The Moon sits in Cancer — home, nostalgia, found family — the same sign the Sun entered the day ILTC began. Full circle. (Kallah and CLTC 3: welcome to day two, hope you like drama.) Say the thing. Blame the planets. 🚌💨",
  "rx": true,
  "cazimi": false,
  "big": true
 },
 {
  "m": 7,
  "d": 14,
  "w": "Tuesday",
  "sign": "Cancer",
  "emoji": "🌑",
  "headline": "NEW MOON in Cancer — the second summer begins",
  "vibe": "The sky resets in the sign of home and belonging, right as the new arrivals unpack. Intention-setting night, round two.",
  "detail": "The New Moon lands in Cancer — a fresh lunar cycle in the sign of found family, two days into Kallah and CLTC 3. What June 14 did for the early summer, tonight does for the late summer. Set the intention. (Retrograde reminder: intentions yes, unsent drafts to your ex, no.)",
  "rx": true,
  "cazimi": false,
  "big": true
 },
 {
  "m": 7,
  "d": 15,
  "w": "Wednesday",
  "sign": "Leo",
  "emoji": "🌒",
  "headline": "Uranus sextile Neptune — the once-a-generation hum",
  "vibe": "A rare, slow background aspect turns exact: invention meets imagination. Big ideas feel weirdly possible this week.",
  "detail": "Uranus (breakthroughs) and Neptune (dreams) form an exact sextile — an aspect so slow it defines eras, not days. You won't feel it like a Moon mood, but this week's brainstorms have unusual horsepower. The Moon enters Leo in the evening: dream big, then perform it.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 16,
  "w": "Thursday",
  "sign": "Leo",
  "emoji": "🌒",
  "headline": "Leo Moon — the new groups find their voice",
  "vibe": "Confidence day for the fresh arrivals. First inside jokes achieve permanence.",
  "detail": "A waxing crescent in Leo — courage, play, and a touch of theater. The best day so far for the new session's shy kids to step forward. Retrograde still on: triple-check the schedule before announcing it.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 17,
  "w": "Friday",
  "sign": "Virgo",
  "emoji": "🌒",
  "headline": "Uranus trine Pluto — deep power, quietly",
  "vibe": "Another generational aspect turns exact. Transformation energy under everything, like a bass note.",
  "detail": "Uranus trines Pluto — revolution and regeneration cooperating for the first time in decades. Combined with a get-it-done Virgo Moon (from 8:07 PM Thursday), this is a stretch where changes made now actually stick. A very good week to become the person you were planning to become.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 18,
  "w": "Saturday",
  "sign": "Virgo",
  "emoji": "🌒",
  "headline": "Virgo Moon — Shabbat, but organized",
  "vibe": "Rest, but make it tidy. The clipboard people are thriving.",
  "detail": "The Moon works through Virgo, the sign of service and detail. Low-drama, high-competence day. Mercury retrograde's classic mix-ups are still around — Virgo Moon is the antidote: check the list twice.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 19,
  "w": "Sunday",
  "sign": "Libra",
  "emoji": "🌒",
  "headline": "Moon enters Libra — social reshuffle",
  "vibe": "One week into the new session: friend groups gently reorganize themselves. Everyone's a diplomat today.",
  "detail": "The Moon enters partnership-minded Libra at 12:56 AM Eastern. First Quarter Moon midweek energy: the 'do the work' phase of the new lunar cycle. Alliances formed this weekend have staying power.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 20,
  "w": "Monday",
  "sign": "Libra",
  "emoji": "🌒",
  "headline": "JUPITER'S BIG DAY — trine Neptune, opposite Pluto",
  "vibe": "The luckiest planet makes two massive aspects at once: dream-big meets power-struggle. Ambition is in the water supply.",
  "detail": "A genuinely rare double: Jupiter trines Neptune (vision, idealism, luck for dreamers) AND opposes Pluto (power, intensity, empires) on the same day. Astrologers circle days like this in red. Big plans hatched today have unusual gravity — just watch the ego arms race at the leadership activity.",
  "rx": true,
  "cazimi": false,
  "big": true
 },
 {
  "m": 7,
  "d": 21,
  "w": "Tuesday",
  "sign": "Scorpio",
  "emoji": "🌓",
  "headline": "Jupiter sextile Uranus — lucky lightning",
  "vibe": "Third Jupiter aspect in two days. Sudden opportunities, happy accidents, right-place-right-time energy.",
  "detail": "Jupiter sextile Uranus is the 'pleasant surprise' transit — luck arriving sideways. The Moon dives into Scorpio at 9:34 AM Eastern, adding intensity to everything. Say yes to the unexpected invitation today.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 22,
  "w": "Wednesday",
  "sign": "Scorpio",
  "emoji": "🌓",
  "headline": "Neptune sextile Pluto + Leo season on the doorstep",
  "vibe": "The last of the week's giant slow aspects, and the Sun packs its bags for Leo. The sky's gears are all turning at once.",
  "detail": "Neptune sextile Pluto rounds out an extraordinary week of outer-planet geometry — dreams and depth cooperating. The Sun finishes Cancer season tonight. And tomorrow… the microwave news everyone's been waiting for.",
  "rx": true,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 23,
  "w": "Thursday",
  "sign": "Scorpio",
  "emoji": "🌔",
  "headline": "MERCURY GOES DIRECT — THE MICROWAVE CLOSES AT 5:57 PM",
  "vibe": "IT'S OVER. After 24 days, Mercury stations direct in Cancer. The door swings shut, the light comes on, the popcorn button works again.",
  "detail": "At 5:57 PM Eastern, Mercury stations direct at 16° Cancer, ending the retrograde that began June 29. Give it a beat — the first days after a station are wobbly ('retrograde storm') while Mercury gets back up to speed, and the post-shadow runs to August 6. But officially, tonight: CLOSED. Leo season also begins today — the Sun enters its favorite sign. The sky flips from rewind to play in one afternoon.",
  "rx": true,
  "cazimi": false,
  "big": true
 },
 {
  "m": 7,
  "d": 24,
  "w": "Friday",
  "sign": "Sagittarius",
  "emoji": "🌔",
  "headline": "First direct day — trust, but verify",
  "vibe": "The microwave is closed but still beeping suspiciously. Plans start un-breaking themselves.",
  "detail": "Mercury is direct but barely moving — day one of the recovery. The Moon blazes into Sagittarius (from 9:07 PM Thursday): optimism returns on schedule. Lost items from the last three weeks begin mysteriously reappearing.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 25,
  "w": "Saturday",
  "sign": "Sagittarius",
  "emoji": "🌔",
  "headline": "Sagittarius Moon — the exhale",
  "vibe": "First full weekend with a closed microwave since June. The whole camp feels 15% lighter.",
  "detail": "A buoyant Sagittarius Moon, a direct Mercury, and Leo-season sunshine. The sky's version of a clean bill of health. Big songs tonight.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 26,
  "w": "Sunday",
  "sign": "Capricorn",
  "emoji": "🌔",
  "headline": "THE NODES SHIFT — a new 18-month era (CLTC 4 arrives)",
  "vibe": "The Moon's nodes change signs — the sky's slow compass swings to Aquarius/Leo — on the exact day CLTC 4 begins. New era, literally.",
  "detail": "The North Node enters Aquarius and the South Node enters Leo, resetting the sky's collective 'growth direction' for the next year and a half — toward community, groups, and the future. It happens once every 18 months, and CLTC 4 arrives ON it. The Moon enters Capricorn at 9:44 AM: ambitious first steps. (CLTC 3: one more day — finish strong.)",
  "rx": false,
  "cazimi": false,
  "big": true
 },
 {
  "m": 7,
  "d": 27,
  "w": "Monday",
  "sign": "Capricorn",
  "emoji": "🌔",
  "headline": "Capricorn Moon — CLTC 3's summit day",
  "vibe": "CLTC 3 graduates under the achievement Moon, with the Full Moon building. Earned pride everywhere.",
  "detail": "The Moon in Capricorn — the sign of mountains climbed — closes out CLTC 3's session while the nearly-full Moon swells overhead. For the CLTC 4 newcomers it's a structured, focused day two. For the departing bus: look up tonight. That glow is yours.",
  "rx": false,
  "cazimi": false,
  "big": true
 },
 {
  "m": 7,
  "d": 28,
  "w": "Tuesday",
  "sign": "Capricorn",
  "emoji": "🌔",
  "headline": "Almost-Full Moon — the buildup",
  "vibe": "Emotions inflate like a balloon before tomorrow's Full Moon in Aquarius. Group feelings, incoming.",
  "detail": "The Moon finishes Capricorn and slips into Aquarius at 9:46 PM Eastern, hours before turning full. Sleep may come slow — the brightest nights of the cycle start now.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 29,
  "w": "Wednesday",
  "sign": "Aquarius",
  "emoji": "🌕",
  "headline": "FULL MOON in Aquarius — the friendship moon",
  "vibe": "Peak Moon in the sign of community — mid-Kallah, early CLTC 4. Group bonds hit their emotional high-water mark tonight.",
  "detail": "The Full Moon lands in Aquarius, the sign of collectives, ideals, and chosen community — the same sign the North Node just entered. Full Moons are culminations: for Kallah it's the week everything peaks; for CLTC 4 it's a spectacular welcome. It's also the first Full Moon of the summer with a CLOSED microwave. Enjoy the clarity.",
  "rx": false,
  "cazimi": false,
  "big": true
 },
 {
  "m": 7,
  "d": 30,
  "w": "Thursday",
  "sign": "Aquarius",
  "emoji": "🌖",
  "headline": "Aquarius Moon — the afterglow",
  "vibe": "Full-Moon hangover, community edition. Everyone's a little raw and a lot closer.",
  "detail": "The Moon wanes through Aquarius after last night's peak. Big-group feelings settle into something steadier. Good day for the conversations the Full Moon started.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 7,
  "d": 31,
  "w": "Friday",
  "sign": "Pisces",
  "emoji": "🌖",
  "headline": "Moon enters Pisces — July's soft landing",
  "vibe": "The month ends the way it needs to: gently. Music hits harder, goodbyes start pre-loading.",
  "detail": "The Moon drifts into Pisces at 8:13 AM Eastern. July — the wildest astrological month of the summer — closes with the zodiac's most sentimental Moon. Kallah: three days left. Feel them.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 8,
  "d": 1,
  "w": "Saturday",
  "sign": "Pisces",
  "emoji": "🌖",
  "headline": "Pisces Moon — Shabbat of feelings",
  "vibe": "The last full Shabbat of Kallah under the dreamiest Moon there is. Bring tissues to song session.",
  "detail": "A slow, tender Pisces Moon day. August arrives quietly. For Kallah the countdown is real now; for CLTC 4 the session is just finding its groove — same sky, two different stories.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 8,
  "d": 2,
  "w": "Sunday",
  "sign": "Pisces",
  "emoji": "🌖",
  "headline": "Pisces to Aries — sentiment, then sparks",
  "vibe": "Soft morning, fired-up evening. The Moon switches from tears to adrenaline at 4:36 PM.",
  "detail": "The Moon finishes Pisces and charges into Aries in the late afternoon. Kallah's second-to-last day gets both flavors: the misty-eyed photo scroll AND the 'let's make tonight legendary' energy.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 8,
  "d": 3,
  "w": "Monday",
  "sign": "Aries",
  "emoji": "🌖",
  "headline": "Kallah's finale — an Aries Moon goodbye",
  "vibe": "The boldest Moon in the zodiac for the bravest kind of day. Loud goodbyes, fierce hugs, zero regrets.",
  "detail": "Kallah ends under an Aries Moon — courage, fire, and forward motion. Aries goodbyes don't linger; they promise. Mercury is direct, the microwave is closed, and the sky's message is unambiguous: take what you built here and GO. (CLTC 4: the Poconos are all yours now.)",
  "rx": false,
  "cazimi": false,
  "big": true
 },
 {
  "m": 8,
  "d": 4,
  "w": "Tuesday",
  "sign": "Aries",
  "emoji": "🌖",
  "headline": "Aries Moon — CLTC 4 turns the intensity up",
  "vibe": "The camp is quieter but the energy isn't. Competitive spirit finds new outlets.",
  "detail": "A full Aries Moon day for the one program still standing. Last Quarter Moon approaching: the lunar cycle enters its 'refine and adjust' phase, matching a session hitting its stride.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 8,
  "d": 5,
  "w": "Wednesday",
  "sign": "Taurus",
  "emoji": "🌗",
  "headline": "Moon enters Taurus — the comfort era",
  "vibe": "Snacks, steadiness, and the best sleep of the session. The sky recommends seconds at dinner.",
  "detail": "The Moon settles into Taurus at 10:35 PM Tuesday night. Two grounded days ahead — the astrological equivalent of a weighted blanket.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 8,
  "d": 6,
  "w": "Thursday",
  "sign": "Taurus",
  "emoji": "🌘",
  "headline": "Mercury exits the retrograde shadow — fully repaired",
  "vibe": "The LAST trace of June's retrograde clears. The microwave passes final inspection. Appliance drama: officially over for the summer.",
  "detail": "Mercury finally re-crosses the degree where the June 29 retrograde began, closing the 'post-retrograde shadow.' In plain terms: the communication weirdness that started June 12 is completely, certifiably done. CLTC 4 gets the only fully retrograde-free stretch of the entire summer. Use it wisely: send the risky text.",
  "rx": false,
  "cazimi": false,
  "big": true
 },
 {
  "m": 8,
  "d": 7,
  "w": "Friday",
  "sign": "Gemini",
  "emoji": "🌘",
  "headline": "Moon enters Gemini — chatter Shabbat",
  "vibe": "The talkative Moon returns for the season's final Shabbat prep. Voices carry across the lake.",
  "detail": "The Moon enters Gemini at 2:07 AM Eastern — words, jokes, connection. With Mercury clean and direct, communication actually works now. Wild concept.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 8,
  "d": 8,
  "w": "Saturday",
  "sign": "Gemini",
  "emoji": "🌘",
  "headline": "Gemini Moon — the last full weekend",
  "vibe": "Inside jokes reach their final form. The group chat's greatest-hits era.",
  "detail": "A social Gemini Moon carries the last full weekend of BBYO summer 2026. The waning crescent overhead means the cycle is closing — and something big is coming Wednesday. The sky is saving its best exit.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 8,
  "d": 9,
  "w": "Sunday",
  "sign": "Cancer",
  "emoji": "🌘",
  "headline": "Moon enters Cancer — the feelings arrive early",
  "vibe": "Three days left. The home-and-belonging Moon shows up right on cue.",
  "detail": "The Moon enters Cancer at 3:45 AM Eastern — the same sign that hosted the summer's two New Moons and all that retrograde drama. One last visit to the feelings sign before the finale.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 8,
  "d": 10,
  "w": "Monday",
  "sign": "Cancer",
  "emoji": "🌘",
  "headline": "Cancer Moon — gratitude day",
  "vibe": "The 'I can't believe it's almost over' conversations begin. Let them.",
  "detail": "A waning Cancer Moon two days before a solar eclipse is the sky at its most reflective. Photos get taken of everything. Addresses get exchanged like contraband.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 8,
  "d": 11,
  "w": "Tuesday",
  "sign": "Leo",
  "emoji": "🌘",
  "headline": "Moon enters Leo — eclipse eve",
  "vibe": "The Moon joins the Sun's sign and goes almost completely dark. Tomorrow, it swallows the Sun whole.",
  "detail": "The Moon slips into Leo at 4:38 AM Eastern and vanishes into the Sun's glare — the darkest possible night before the most dramatic possible ending. Second-to-last day energy: loud on the outside, tender underneath.",
  "rx": false,
  "cazimi": false,
  "big": false
 },
 {
  "m": 8,
  "d": 12,
  "w": "Wednesday",
  "sign": "Leo",
  "emoji": "🌑",
  "headline": "TOTAL SOLAR ECLIPSE — CLTC 4's finale. The sky ends the summer itself.",
  "vibe": "On the actual last day of BBYO summer 2026, the Moon covers the Sun completely. A TOTAL SOLAR ECLIPSE, in Leo, on departure day. This is not a joke. This is the real sky.",
  "detail": "Today the New Moon in Leo turns into a total solar eclipse — the Moon passing directly in front of the Sun (totality tracks over Iceland and Spain; from Pennsylvania it's a story you're inside of, not a view). Eclipses are the sky's chapter breaks: astrologers call them fate's fast-forward button, and this one lands in Leo — the sign of courage, hearts, and main characters — on the day the last buses pull away. Whatever begins today, begins BIG. The microwave is closed. The summer is complete. The sky, frankly, showed off. 🌑🚌✨",
  "rx": false,
  "cazimi": false,
  "big": true
 }
];
const PROGRAMS = {
 "cltc1": {
  "name": "CLTC 1",
  "range": "June 7 – 22",
  "start": [
   6,
   7
  ],
  "end": [
   6,
   22
  ]
 },
 "cltc2": {
  "name": "CLTC 2",
  "range": "June 21 – July 6",
  "start": [
   6,
   21
  ],
  "end": [
   7,
   6
  ]
 },
 "iltc": {
  "name": "ILTC",
  "range": "June 21 – July 13",
  "start": [
   6,
   21
  ],
  "end": [
   7,
   13
  ]
 },
 "kallah": {
  "name": "International Kallah",
  "range": "July 12 – August 3",
  "start": [
   7,
   12
  ],
  "end": [
   8,
   3
  ]
 },
 "cltc3": {
  "name": "CLTC 3",
  "range": "July 12 – 27",
  "start": [
   7,
   12
  ],
  "end": [
   7,
   27
  ]
 },
 "cltc4": {
  "name": "CLTC 4",
  "range": "July 26 – August 12",
  "start": [
   7,
   26
  ],
  "end": [
   8,
   12
  ]
 }
};
const MONTHS = [
 {
  "name": "September 2026",
  "rating": "great",
  "bestDays": "Sept 10–11 (goals) · Sept 14–25 (reviews)",
  "why": "The cleanest month of the whole school year. Every planet that matters is direct. The New Moon on Sept 10 lands in VIRGO — the zodiac's checklist sign — which is comically perfect for goal-setting meetings. Do your heavy annual planning HERE.",
  "avoid": "Sept 26 (Full Moon — emotions run high in the conference room)."
 },
 {
  "name": "October 2026",
  "rating": "avoid",
  "bestDays": "Oct 1–2 only",
  "why": "Venus goes retrograde Oct 3 (through Nov 13) — the planet of harmony, reversing through the signs of relationships. Feedback conversations land wrong all month. Then Mercury JOINS it in retrograde Oct 24. The microwave is open AND the thermostat is broken.",
  "avoid": "Oct 3 onward for reviews; Oct 24 – Nov 13 for everything (double retrograde)."
 },
 {
  "name": "November 2026",
  "rating": "caution",
  "bestDays": "Nov 17–20",
  "why": "Mercury AND Venus both station direct on Nov 13 — the sky's biggest exhale of the season. Give the dust three days to settle, then you have a lovely window: Nov 17–20, everything direct, before the Full Moon on Nov 24 and holiday brain sets in.",
  "avoid": "Nov 1–13 (double retrograde still on) · Nov 24 (Full Moon)."
 },
 {
  "name": "December 2026",
  "rating": "great",
  "bestDays": "Dec 8–9 (goals) · Dec 10–18 (reviews)",
  "why": "Fully clean skies again. The New Moon on Dec 8 is in SAGITTARIUS — the big-vision sign — ideal for setting spring-semester goals while everyone still has energy. Wrap reviews by the 18th; the Full Moon hits Dec 23 along with everyone's vacation brain.",
  "avoid": "Dec 23 (Full Moon) and honestly anything after the 19th."
 },
 {
  "name": "January 2027",
  "rating": "fine",
  "bestDays": "Jan 7–8 (goals — the year's power slot)",
  "why": "The New Moon on Jan 7 is in CAPRICORN — the literal sign of ambition, career, and long-term plans. It's the single best goal-setting date of the winter. But move fast: Mars goes retrograde Jan 10 (through April 1), which slows the DOING. Set goals Jan 7–8; expect execution to crawl until spring.",
  "avoid": "Jan 22 (Full Moon) · after Jan 10, don't launch big new initiatives — talk yes, sprint no."
 },
 {
  "name": "February 2027",
  "rating": "avoid",
  "bestDays": "Feb 4–5, if you absolutely must",
  "why": "The worst month on the calendar. A solar eclipse Feb 6, Mercury retrograde Feb 9 – Mar 3 (microwave OPEN), a lunar eclipse Feb 20, and Mars still retrograde the whole time. Astrologers do not sign contracts, start jobs, or give performance reviews in this. Just vibe until March.",
  "avoid": "Feb 6 (eclipse), Feb 9 – Mar 3 (Mercury Rx), Feb 20 (eclipse). So… February."
 },
 {
  "name": "March 2027",
  "rating": "fine",
  "bestDays": "Mar 8–19",
  "why": "Mercury stations direct Mar 3, and the New Moon on Mar 8 opens a genuinely good stretch: Mar 8–19 for reviews and re-set conversations. Mars is still retrograde until April, so keep the outcomes conversational — insight now, action plans in April.",
  "avoid": "Mar 1–3 (Mercury still wobbling) · Mar 22 (Full Moon)."
 },
 {
  "name": "April 2027",
  "rating": "great",
  "bestDays": "Apr 6–7 — the best days of the entire year",
  "why": "Mars finally goes direct April 1, and the New Moon on April 6 lands in ARIES — the sign of pure initiative — with every personal planet moving forward. This is the sky's green-light day of the school year. Goal-setting on Apr 6–7 gets cosmic tailwind; reviews any time Apr 5–16.",
  "avoid": "Apr 20 (Full Moon)."
 },
 {
  "name": "May 2027",
  "rating": "fine",
  "bestDays": "May 6 (goals) · May 3–14 (reviews)",
  "why": "The New Moon on May 6 is in TAURUS — practical, budget-minded, sustainable — right for end-of-year wrap-ups and summer planning. Close everything out by mid-May: Mercury's next retrograde shadow creeps in late May ahead of the June 10 retrograde.",
  "avoid": "May 20 (Full Moon) · after May 24 (retrograde shadow returns — the microwave starts rattling)."
 }
];
